### PR TITLE
UI Refresh and Tackle the slowness

### PR DESCRIPTION
**Pull request by flipmcf**
see https://community.plone.org/t/plonekeywordmanager-maintenance/14477/5

issue #17 
issue #45

### CODE REVIEW

**Comment by jensens** [comment]
I need some days to get this done, but I am going to put your branch on the test server of a client project with many keywords that needs much management and then I'll come back with a review. But I am already sure it will be awesome!

**Comment by flipmcf** [comment]
Well, I tagged Issue #49 on also.   We need that for our install. 

I feel like I'm slowly scope creeping this PR.  sorry.

**Comment by petschki** [comment]
Hey great to see some love on KeywordManager! Need this here too.

I'd stretch the scope of this PR even a bit more and implement Github Actions like for example here https://github.com/collective/collective.taxonomy/blob/master/.github/workflows/main.yml

**Comment by flipmcf** [comment]
Fine.  "While we're at it".

I'd like to create a feature that highlights the white space in keywords.  Currently, it's impossible to tell that "foo" and " foo" and "foo " are different keywords when shown on the page (and which one is the correct one to merge to)  I'll create a new enhancement ticket to talk about it.

**Comment by flipmcf** [comment]
> Hey great to see some love on KeywordManager! Need this here too.
> 
> I'd stretch the scope of this PR even a bit more and implement Github Actions like for example here https://github.com/collective/collective.taxonomy/blob/master/.github/workflows/main.yml

is this #37 ?

**Comment by flipmcf** [comment]
And I hope I can mission creep even more:

#52

**Comment by petschki** [comment]
> @petschki
> 
> > Hey great to see some love on KeywordManager! Need this here too.
> > I'd stretch the scope of this PR even a bit more and implement Github Actions like for example here https://github.com/collective/collective.taxonomy/blob/master/.github/workflows/main.yml
> 
> is this #37 ?

yes it is

**Review by jensens — CHANGES_REQUESTED** [review]
I tested it at my customers site who has lots of keywords in lots of different fields. Overall: It works like a charm, is super fast and way better to work with than ever before.

I tested it on Pone 5.2.6 and only found minor possible improvements:
- the delimiter line between keyword selection and button is a bit confusing.
- button text is really long: Rename All Selected Keywords". Same for "Delete...". I think "Rename" or "Delete" would be enough - there is no other possible context.
- I think your PR targets Plone 6. Would it be possible to add some classes, so label positioning in Plone 5.2 works? I think its not much more.
- Click on search loads a new site. Idea: Open result in modal? 

Good work! I love it!

**Comment by flipmcf** [comment]
> * I think your PR targets Plone 6. Would it be possible to add some classes, so label positioning in Plone 5.2 works? I think its not much more.

I'm targeting my 5.2 install actually.  I'm not going for 6.  (should I?  I don't want to.)   

Adding classes to labels is not a big deal, but I do want to be on the same page strategically if plone 6 is a concern.

**Comment by jensens** [comment]
@agitator told me it should be possible to have code targeting both, so he may explain? *poke*

**Comment by flipmcf** [comment]
In review, this PR will address:

#17 - the main reason for the PR - performance and UX with unusually large numbers of keywords
#45 -  the empty ( '' ) keyword is not displayed.
#49 - make keyword manager work for subsites:   'localhost:8080/Plone/english'
#37 - update CI (todo)
#51 - Make keyword whitespace visible
#52 - redirect url after form post goes back to original query and page
#53 - portal status message fixed

And also the untracked enhancement that adds the keyword cardinality next to the keyword

In the effort to draw a line in the sand and end the scope creep, I will not address (but I'm noting)

* Enhancement: open search results in a modal.
* Plone 6 compat.
* Fixing Py 2.7 Unicode decode issues.

let's leave some work for 3.0.5 and get a release out.

**Comment by jensens** [comment]
@flipmcf Please mark as ready for review and press merge! Or is something missing? I do not think so.

**Comment by jensens** [comment]
@flipmcf as you fiffle with Github actions: The buttonz on top of README.rst need some love too.

**Comment by flipmcf** [comment]
> Please mark as ready for review and press merge! Or is something missing? I do not think so.

I'd like to get the workflow and README.rst buttons working as the previous travis CI did.

We're running tests, but coverage and black are not running yet.

Also, this is the first time I'm diving into readme badges - I'm going to have to learn a little today about that.

**Comment by flipmcf** [comment]
Coveralls updated and working with google CI.   (wipes forehead)

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
Thanks for the awesome work @flipmcf !

**Pull request merged**
