### PR TITLE
cleanups + utility

### LINKED ISSUE #15: Deprecate tool and convert to utility
It would be a good idea to convert the tool into a global non-persistent utility.  This would be more in keeping with modern Plone usage

### PR DESCRIPTION
**Pull request by gforcada**
Fixes #15 

Turn the persistent tool into a utility 🎉 

As a bonus I did quite a few cleanups, l made each of them in a separate commit to easily review and revert any if it is not meant to get merged

Todos:
- [x] add an upgrade step to remove the persistent tool
- [x] update the change log

### CODE REVIEW

**Comment by flipmcf** [comment]
Thanks for this Gil!

It's early morning here in the US, so before I dive in to the review, can I (get coffee) and ask why a utility is better suited than a tool? 

I want to really understand your thoughts, the problem, and your solution.   If anything, I want to learn from this myself!

Do you have a goal here or is this cleanup for future-proofing?

I'm down for the change, this is very old stuff, just walk me through your thoughts.

**Comment by jensens** [comment]
Since PloneKeywordManager does not store anything, a non persistent utility is perfect. At the time of writing (about 19 years ago) this concept was not born at all. That is the reason why it is as it is. I think this is nice step of modernization and I am +1 to merge this.

I even would skip any deprecation warning and just go for a new major version. 

Anyway, an upgrade step is absolutely mandatory, otherwise we are running Plone sites with a zombie object.

**Comment by gforcada** [comment]
@jensens deprecations not added, and upgrade step added 👍🏾

**Comment by gforcada** [comment]
@jensens thanks for merging! may we make a new release? 😄 I can cut it, though I don't have access on pypi for it. My username on pypi is `gilforcada`.

**Comment by jensens** [comment]
@gforcada invite sent!

**Comment by gforcada** [comment]
Thanks! I created 5.0.0a1 @flipmcf as you have it already on production, I guess, could you try the upgrade step and check that everything works fine? I will do the same with a fresh new installation as well 😄

**Pull request merged**
