### PR TITLE
add checkbox to show/hide related keywords

### PR DESCRIPTION
**Pull request by CorySanin**
Optionally de-clutter the list of keywords

### CODE REVIEW

**Comment by tkimnguyen** [comment]
@hvelarde @jensens do you want to weigh in on this?

**Comment by jensens** [comment]
Sorry, atm this package not on my priority list.

**Comment by CorySanin** [comment]
not a problem 👍

**Comment by hvelarde** [comment]
I can check this later, but tests must past and a changelog entry must be added.

do something like this, please: https://github.com/collective/collective.fingerpointing/commit/8c61efac4e3e96c40b3901110745ff77c37c5cae

**Comment by CorySanin** [comment]
[This](https://github.com/JBKahn/flake8-print/issues/33) is the reason it fails to build. Will add changelog entry.

**Comment by hvelarde** [comment]
to fix the error in Travis see: https://github.com/collective/collective.lazysizes/commit/5a6cb14107c297594e2b9504ae346350d4468e23

on the other side, have you tested this with latest Plone 5.1?

**Pull request merged**
